# generated by datamodel-codegen:
#   filename:  tmppqixg91h.json
#   timestamp: 2025-10-14T09:57:53+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional, Union

from pydantic import BaseModel, Field


class ResponseType(Enum):
    """Enum representing the type of response expected from the voice control system."""

    CARD_UPDATE = "card_update"
    FILTER = "filter"
    AUTO_INTENT = "auto"
    UNKNOWN = "unknown"


class ChecklistItem(BaseModel):
    item_id: Optional[int] = Field(
        None,
        description="Identifiant unique de l'élément de la checklist. Doit être vide dans le cas d'un nouvel élément.",
    )
    item_name: Optional[str] = Field(None, description="Description de l'élément de la checklist.")
    is_done: Optional[bool] = Field(None, description="Indique si l'élément est complété.")


class Priority(Enum):
    low = "low"
    medium = "medium"
    high = "high"


class Label(BaseModel):
    label_id: int = Field(..., description="Identifiant unique du libellé.")


class CardEditResponse(BaseModel):
    response_type: ResponseType = Field(default=ResponseType.CARD_UPDATE, description="Type de réponse.")
    task_id: Optional[int] = Field(
        None,
        description="Identifiant unique de la tâche. Doit être vide dans le cas d'une nouvelle tâche.",
    )
    title: str = Field(..., description="Titre de la tâche.")
    description: Optional[str] = Field(None, description="Description détaillée de la tâche.")
    checklist: Optional[List[ChecklistItem]] = Field(None, description="Liste des éléments à vérifier pour la tâche.")
    due_date: Optional[str] = Field(None, description='Date limite de la tâche au format "yyyy-mm-dd".')
    list_id: Optional[int] = Field(None, description="Identifiant de la liste à laquelle appartient la tâche.")
    priority: Optional[Priority] = Field(None, description="Niveau de priorité de la tâche.")
    assignee_id: Optional[int] = Field(None, description="Identifiant de l'utilisateur assigné à la tâche.")
    labels: Optional[List[Label]] = Field(None, description="Liste des libellés associés à la tâche.")


class CardId(BaseModel):
    id: int = Field(..., description="Identifiant unique de la carte.")


class CardFilterResponse(BaseModel):
    response_type: ResponseType = Field(default=ResponseType.FILTER, description="Type de réponse.")
    description: str = Field(..., description="Description du filtre appliqué basée sur la demande de l'utilisateur.")
    cards: List[CardId] = Field(
        ...,
        description="Liste des cartes qui correspondent au filtre. Chaque carte est représentée par un objet contenant son identifiant.",
    )


class AutoIntentResponse(BaseModel):
    """Response model when the system needs to analyze user intent to decide between card_update and filter."""

    response_type: ResponseType = Field(default=ResponseType.AUTO_INTENT, description="Type of response.")
    action: ResponseType = Field(..., description="Action decided by the system: card_update or filter.")
    confidence: float = Field(..., description="Confidence level of the decision (0.0 to 1.0).")


class UnknownResponse(BaseModel):
    """Response model when the system cannot understand the user's request."""

    response_type: ResponseType = Field(default=ResponseType.UNKNOWN, description="Type of response.")


# Union type for all possible responses
VoiceControlResponse = Union[CardEditResponse, CardFilterResponse, UnknownResponse]
